export const vegaShopLocators = {
    productsFirstCategory: '.megamenu .with-sub-menu.furniture1-rooms > a span strong',
    subcategoryDropdownMenu: '.content',
    firstSubCategoryLink: 'a[href="am/herhowstatsowytsner"]',
    secondSubCategoryLink: 'a[href="am/smart-box-hamakarger"]',
    productName: '.product-list .right .name a',
    productPrice: '.product-list .right .price-new',
    addToCartBtn: 'a.btn-add-to-cart[onclick^="cart.add"]',
    Product: 'a.mousehoverimage',
    addToCartPopupMessage: '.d-flex > .left > .tt-modal-messages',
    popupProductTitle: '.tt-modal-product .tt-title a',
    cartProductsTotalCount: '#total_count_ajax',
    cartToggleBtn: '#cart_block .cart-heading.dropdown-toogle',
    cartDropDownMenu: '#cart_block .dropdown-menu.show',
    popupTotalPrice: '.tt-total #total_amount_ajax',
    productNameInCart: '.mini-cart-info > table > tbody > tr > td.name > a',
    cartTotalPrice: '.mini-cart-total > table > tbody > tr:nth-child(2) > td.right:last-child',
    closePopupBtn: 'a.btn.btn-border.btn-close-popup',
    openCartBtn: '.open-cart',
    checkoutBtn: 'a.btn[href="https://vega.am/am/checkout/"]'
}
